version: '3.8'

services:
  minio:
    image: docker.io/minio/minio:RELEASE.2022-10-29T06-21-33Z
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rootadmin
      MINIO_ROOT_PASSWORD: supersecretpassword123
    volumes:
      - minio_data:/data

  postgres:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: photo_may
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:1@postgres:5432/photo_may
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: rootadmin
      MINIO_SECRET_KEY: supersecretpassword123
    depends_on:
      - postgres
      - minio
    volumes:
      - "./fornt_for_rasberry/dist:/fornt_for_rasberry/dist"

volumes:
  minio_data:
  postgres_data: